const palette = {
    'gray-10': '#FFFFFF',
    'gray-15': '#FDFDFD',
    'gray-20': '#FAFAFA',
    'gray-25': '#F7F7F7',
    'gray-30': '#F3F3F3',
    'gray-35': '#F1F1F1',
    'gray-40': '#EBEBEB',
    'gray-45': '#E3E3E3',
    'gray-50': '#D4D4D4',
    'gray-55': '#CCCCCC',
    'gray-60': '#B5B5B5',
    'gray-65': '#8A8A8A',
    'gray-70': '#616161',
    'gray-80': '#4A4A4A',
    'gray-90': '#303030',
    'gray-100': '#1A1A1A',

    'lightblue-10': '#FBFDFF',
    'lightblue-15': '#F2F9FF',
    'lightblue-20': '#EAF4FF',
    'lightblue-25': '#E0F0FF',
    'lightblue-30': '#D5EBFF',
    'lightblue-35': '#CAE6FF',
    'lightblue-40': '#C0E1FF',
    'lightblue-45': '#A8D8FF',
    'lightblue-50': '#91D0FF',
    'lightblue-55': '#51C0FF',
    'lightblue-60': '#0094D5',
    'lightblue-65': '#007CB4',
    'lightblue-70': '#00679B',
    'lightblue-80': '#00527C',
    'lightblue-90': '#003A5A',
    'lightblue-100': '#002133',

    'green-10': '#F8FFFB',
    'green-15': '#E3FFED',
    'green-20': '#CDFEE1',
    'green-25': '#B4FED2',
    'green-30': '#92FEC2',
    'green-35': '#63FDB0',
    'green-40': '#38FAA3',
    'green-45': '#35EE9B',
    'green-50': '#32E193',
    'green-55': '#2ED389',
    'green-60': '#32A06E',
    'green-65': '#29845A',
    'green-70': '#136F45',
    'green-80': '#0C5132',
    'green-90': '#083D25',
    'green-100': '#092A1B',

    'yellow-10': '#FFFDF6',
    'yellow-15': '#FFF8DB',
    'yellow-20': '#FFF4BF',
    'yellow-25': '#FFEF9D',
    'yellow-30': '#FFEB78',
    'yellow-35': '#FFE600',
    'yellow-40': '#FFD954',
    'yellow-45': '#FFD233',
    'yellow-50': '#FFCC33',
    'yellow-55': '#E8B500',
    'yellow-60': '#B58D00',
    'yellow-65': '#8C6D00',
    'yellow-70': '#6B5400',
    'yellow-80': '#5B4700',
    'yellow-90': '#403300',
    'yellow-100': '#1F1C00',

    'purple-10': '#FDFDFF',
    'purple-15': '#F8F7FF',
    'purple-20': '#F3F1FF',
    'purple-25': '#EFECFF',
    'purple-30': '#E9E5FF',
    'purple-35': '#E4DEFF',
    'purple-40': '#DFD9FF',
    'purple-45': '#D4CCFF',
    'purple-50': '#C7BCFF',
    'purple-55': '#AA95FF',
    'purple-60': '#9474FF',
    'purple-65': '#8051FF',
    'purple-70': '#7126FF',
    'purple-80': '#5700D1',
    'purple-90': '#3B0093',
    'purple-100': '#1C004F',

    'blue-10': '#FCFDFF',
    'blue-15': '#F6F8FF',
    'blue-20': '#F0F2FF',
    'blue-25': '#EAEDFF',
    'blue-30': '#E2E7FF',
    'blue-35': '#DBE1FF',
    'blue-40': '#D5DCFF',
    'blue-45': '#C5D0FF',
    'blue-50': '#BAC7FF',
    'blue-55': '#97ADFF',
    'blue-60': '#4188FF',
    'blue-65': '#0071E9',
    'blue-70': '#005BD3',
    'blue-80': '#004299',
    'blue-90': '#002E6A',
    'blue-100': '#001633',

    'red-10': '#FFFBFB',
    'red-15': '#FFF6F6',
    'red-20': '#FFEDEC',
    'red-25': '#FEE9E8',
    'red-30': '#FEE2E1',
    'red-35': '#FEDAD9',
    'red-40': '#FED3D1',
    'red-45': '#FEC3C1',
    'red-50': '#FDB0AC',
    'red-55': '#FD817A',
    'red-60': '#EF4D2F',
    'red-65': '#E51C00',
    'red-70': '#B5260B',
    'red-80': '#8E1F0B',
    'red-90': '#5F1507',
    'red-100': '#2F0A04',

    'orange-10': '#FFFDFA',
    'orange-15': '#FFF7EE',
    'orange-20': '#FFF1E3',
    'orange-25': '#FFEBD5',
    'orange-30': '#FFE4C6',
    'orange-35': '#FFDDB6',
    'orange-40': '#FFD6A4',
    'orange-45': '#FFC06E',
    'orange-50': '#FFA938',
    'orange-55': '#FF9200',
    'orange-60': '#F38303',
    'orange-65': '#DD7A01',
    'orange-70': '#A96404',
    'orange-80': '#825101',
    'orange-90': '#3E2B02',
    'orange-100': '#371E03',

    'teal-10': '#FAFFFE',
    'teal-15': '#E7FCF8',
    'teal-20': '#D7FBF3',
    'teal-25': '#C0F9EF',
    'teal-30': '#A5F7E9',
    'teal-35': '#90F4E3',
    'teal-40': '#92EDDE',
    'teal-45': '#82E3D1',
    'teal-50': '#74DBC8',
    'teal-55': '#17C7A7',
    'teal-60': '#13A389',
    'teal-65': '#0E8470',
    'teal-70': '#086B5A',
    'teal-80': '#095346',
    'teal-90': '#06382F',
    'teal-100': '#05241E',

    'magenta-10': '#FFFDFF',
    'magenta-15': '#FFF5FF',
    'magenta-20': '#FDEFFD',
    'magenta-25': '#FEE7FE',
    'magenta-30': '#FCDFFC',
    'magenta-35': '#FBD7FB',
    'magenta-40': '#FBCFFB',
    'magenta-45': '#F9BEF9',
    'magenta-50': '#F8B1F8',
    'magenta-55': '#F68DF6',
    'magenta-60': '#E156E1',
    'magenta-65': '#C530C5',
    'magenta-70': '#9F269F',
    'magenta-80': '#791A79',
    'magenta-90': '#561056',
    'magenta-100': '#340634',
};

export type ColorKeys =
    | 'color-bg'
    | 'color-bg-alt'
    | 'color-bg-surface'
    | 'color-bg-surface-hover'
    | 'color-bg-surface-selected'
    | 'color-bg-surface-disabled'
    | 'color-bg-surface-success'
    | 'color-bg-surface-warning'
    | 'color-bg-surface-error'
    | 'color-bg-fill'
    | 'color-bg-fill-hover'
    | 'color-bg-fill-disabled'
    | 'color-bg-fill-secondary'
    | 'color-bg-fill-secondary-hover'
    | 'color-bg-fill-tertiary'
    | 'color-bg-fill-tertiary-hover'
    | 'color-bg-fill-success'
    | 'color-bg-fill-warning'
    | 'color-bg-fill-error'
    | 'color-text'
    | 'color-text-secondary'
    | 'color-text-disabled'
    | 'color-text-inverse'
    | 'color-text-on-bg-hover'
    | 'color-text-info'
    | 'color-text-success'
    | 'color-text-warning'
    | 'color-text-error'
    | 'color-text-emphasis'
    | 'color-text-link'
    | 'color-text-link-hover'
    | 'color-text-link-inverse'
    | 'color-icon'
    | 'color-icon-hover'
    | 'color-icon-disabled'
    | 'color-icon-secondary'
    | 'color-icon-secondary-hover'
    | 'color-icon-info'
    | 'color-icon-success'
    | 'color-icon-warning'
    | 'color-icon-error'
    | 'color-icon-inverse'
    | 'color-border'
    | 'color-border-hover'
    | 'color-border-disabled'
    | 'color-border-secondary'
    | 'color-border-tertiary'
    | 'color-border-info'
    | 'color-border-success'
    | 'color-border-warning'
    | 'color-border-error'
    | 'color-border-focus'
    | 'color-material-dimmer';

export const themeColors: Record<'light' | 'dark', { [key in ColorKeys]: string }> = {
    light: {
        'color-bg': palette['gray-10'],
        'color-bg-alt': palette['gray-20'],
        'color-bg-surface': palette['gray-10'],
        'color-bg-surface-hover': palette['gray-25'],
        'color-bg-surface-selected': palette['gray-30'],
        'color-bg-surface-disabled': palette['gray-20'],
        'color-bg-surface-success': palette['green-30'],
        'color-bg-surface-warning': palette['orange-30'],
        'color-bg-surface-error': palette['red-30'],
        'color-bg-fill': palette['yellow-50'],
        'color-bg-fill-hover': palette['yellow-40'],
        'color-bg-fill-disabled': palette['gray-60'],
        'color-bg-fill-secondary': palette['gray-10'],
        'color-bg-fill-secondary-hover': palette['gray-20'],
        'color-bg-fill-tertiary': palette['gray-35'],
        'color-bg-fill-tertiary-hover': palette['gray-40'],
        'color-bg-fill-success': palette['green-50'],
        'color-bg-fill-warning': palette['orange-50'],
        'color-bg-fill-error': palette['red-55'],
        'color-text': palette['gray-100'],
        'color-text-secondary': palette['gray-70'],
        'color-text-disabled': palette['gray-60'],
        'color-text-inverse': palette['gray-10'],
        'color-text-on-bg-hover': palette['gray-45'],
        'color-text-info': palette['lightblue-80'],
        'color-text-success': palette['green-60'],
        'color-text-warning': palette['orange-60'],
        'color-text-error': palette['red-65'],
        'color-text-emphasis': palette['blue-70'],
        'color-text-link': palette['blue-70'],
        'color-text-link-hover': palette['blue-80'],
        'color-text-link-inverse': palette['blue-45'],
        'color-icon': palette['gray-80'],
        'color-icon-hover': palette['gray-90'],
        'color-icon-disabled': palette['gray-55'],
        'color-icon-secondary': palette['gray-65'],
        'color-icon-secondary-hover': palette['gray-70'],
        'color-icon-info': palette['lightblue-60'],
        'color-icon-success': palette['green-60'],
        'color-icon-warning': palette['orange-60'],
        'color-icon-error': palette['red-60'],
        'color-icon-inverse': palette['gray-45'],
        'color-border': palette['gray-45'],
        'color-border-hover': palette['gray-55'],
        'color-border-disabled': palette['gray-40'],
        'color-border-secondary': palette['gray-40'],
        'color-border-tertiary': palette['gray-55'],
        'color-border-info': palette['lightblue-45'],
        'color-border-success': palette['green-30'],
        'color-border-warning': palette['orange-45'],
        'color-border-error': palette['red-45'],
        'color-border-focus': palette['gray-100'],
        'color-material-dimmer': '#1A1A1A85',
    },
    dark: {
        'color-bg': palette['gray-10'],
        'color-bg-alt': palette['gray-20'],
        'color-bg-surface': palette['gray-10'],
        'color-bg-surface-hover': palette['gray-25'],
        'color-bg-surface-selected': palette['gray-30'],
        'color-bg-surface-disabled': palette['gray-20'],
        'color-bg-surface-success': palette['green-30'],
        'color-bg-surface-warning': palette['orange-30'],
        'color-bg-surface-error': palette['red-30'],
        'color-bg-fill': palette['yellow-50'],
        'color-bg-fill-hover': palette['yellow-40'],
        'color-bg-fill-disabled': palette['gray-60'],
        'color-bg-fill-secondary': palette['gray-10'],
        'color-bg-fill-secondary-hover': palette['gray-20'],
        'color-bg-fill-tertiary': palette['gray-35'],
        'color-bg-fill-tertiary-hover': palette['gray-40'],
        'color-bg-fill-success': palette['green-50'],
        'color-bg-fill-warning': palette['orange-50'],
        'color-bg-fill-error': palette['red-55'],
        'color-text': palette['gray-100'],
        'color-text-secondary': palette['gray-70'],
        'color-text-disabled': palette['gray-60'],
        'color-text-inverse': palette['gray-10'],
        'color-text-on-bg-hover': palette['gray-45'],
        'color-text-info': palette['lightblue-80'],
        'color-text-success': palette['green-60'],
        'color-text-warning': palette['orange-60'],
        'color-text-error': palette['red-65'],
        'color-text-emphasis': palette['blue-70'],
        'color-text-link': palette['blue-70'],
        'color-text-link-hover': palette['blue-80'],
        'color-text-link-inverse': palette['blue-45'],
        'color-icon': palette['gray-80'],
        'color-icon-hover': palette['gray-90'],
        'color-icon-disabled': palette['gray-55'],
        'color-icon-secondary': palette['gray-65'],
        'color-icon-secondary-hover': palette['gray-70'],
        'color-icon-info': palette['lightblue-60'],
        'color-icon-success': palette['green-60'],
        'color-icon-warning': palette['orange-60'],
        'color-icon-error': palette['red-60'],
        'color-icon-inverse': palette['gray-45'],
        'color-border': palette['gray-45'],
        'color-border-hover': palette['gray-55'],
        'color-border-disabled': palette['gray-40'],
        'color-border-secondary': palette['gray-40'],
        'color-border-tertiary': palette['gray-55'],
        'color-border-info': palette['lightblue-45'],
        'color-border-success': palette['green-30'],
        'color-border-warning': palette['orange-45'],
        'color-border-error': palette['red-45'],
        'color-border-focus': palette['gray-100'],
        'color-material-dimmer': '#1A1A1A85',
    },
} as const;
